version: "3.9"

services:
  server:
    build: .
    container_name: server
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db

  db:
    image: mysql:latest
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: h23w10
      MYSQL_DATABASE: h23w10

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
