version: '3'

tasks:
  up:
    cmds:
      - docker compose up -d --build

  server:
    cmds:
      - cd cmd/server && go run main.go

  migrate:
    cmds:
      - migrate --path db/migrations --database 'mysql://"$MYSQL_USER":"$MYSQL_PASSWORD"@tcp("$MYSQL_HOST":3306)/"$MYSQL_DATABASE"' --verbose up

  migrate-force:
    cmds:
      - migrate --path db/migrations --database 'mysql://root:h23w10@tcp(localhost:3306)/h23w10' --verbose force 1

  migrate-down:
    cmds:
      - migrate --path db/migrations --database 'mysql://root:h23w10@tcp(localhost:3306)/h23w10' --verbose down

  log:
    cmds:
      - docker compose logs -f server